ShadyRoom_MapScripts::
	.byte 0


ShadyRoom_EventScript_Gentleman::
# 4 "data/maps/ShadyRoom/scripts.pory"
	msgbox ShadyRoom_Text_Gentleman, MSGBOX_NPC
	return


ShadyRoom_EventScript_Assistant::
# 8 "data/maps/ShadyRoom/scripts.pory"
	msgbox ShadyRoom_Text_Gentleman, MSGBOX_NPC
	return


ShadyRoom_EventScript_Merchant::
# 12 "data/maps/ShadyRoom/scripts.pory"
	msgbox ShadyRoom_Text_Gentleman, MSGBOX_NPC
	return


ShadyRoom_EventScript_Abra::
# 16 "data/maps/ShadyRoom/scripts.pory"
	msgbox ShadyRoom_Text_Gentleman, MSGBOX_NPC
	return


ShadyRoom_Text_Gentleman::
# 19 "data/maps/ShadyRoom/scripts.pory"
	.string "Hey.\n"
	.string "What's up?$"
